"""init database: all tables with user profile fields

Revision ID: 0e6a89484a73
Revises: 
Create Date: 2025-12-12 11:31:39.345692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e6a89484a73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(length=100), nullable=False, comment='用户展示昵称（可与username不同）'))
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=False, comment='用户性别（男/女/未知）'))
    op.add_column('user', sa.Column('avatar', sa.Text(), nullable=False, comment='用户头像URL'))
    op.add_column('user', sa.Column('phone', sa.String(length=11), nullable=False, comment='用户手机号（11位，唯一）'))
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
