"""备注（如：add last_login_time to user table）

Revision ID: d68861c80fc6
Revises: 0e6a89484a73
Create Date: 2025-12-12 11:33:20.985289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68861c80fc6'
down_revision: Union[str, Sequence[str], None] = '0e6a89484a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
